$(function(){
    $('#222').click(function(){
       $('#riview').hide();
       $('#qna').show();
       $('#text').hide();
    });
    $('#333').click(function(){
       $('#riview').hide();
       $('#qna').hide();
       $('#text').show();
    });
    $('#111').click(function(){
       $('#riview').show();
       $('#qna').hide();
       $('#text').hide();
    });
    $('#666').click(function(){
       $('#riview').show();
       $('#qna').hide();
       $('#text').hide();
    });
    $('#777').click(function(){
       $('#riview').hide();
       $('#qna').show();
       $('#text').hide();
    });
    $('#888').click(function(){
       $('#riview').hide();
       $('#qna').hide();
       $('#text').show();
    });
   });