$(function(){
    $('#44').click(function(){
       $('.rr1').hide();
       $('#qq').show();
       $('.anso').hide();
    });
    $('#55').click(function(){
       $('.rr1').hide();
       $('#qq').hide();
       $('.anso').show();
    });
    $('#11').click(function(){
       $('.rr1').show();
       $('#qq').hide();
       $('.anso').hide();
    });
    $('#1').click(function(){
       $('.rr1').show();
       $('#qq').hide();
       $('.anso').hide();
    });
    $('#3').click(function(){
       $('.rr1').hide();
       $('#qq').show();
       $('.anso').hide();
    });
    $('#4').click(function(){
       $('.rr1').hide();
       $('#qq').hide();
       $('.anso').show();
    });
   });