$(function(){
    $('#222').click(function(){
       $('#riview').hide();
       $('#qna').fadeIn();
       $('#text').hide();
       
    });
    $('#333').click(function(){
       $('#riview').hide();
       $('#qna').hide();
       $('#text').fadeIn();
    });
    $('#111').click(function(){
       $('#riview').fadeIn();
       $('#qna').hide();
       $('#text').hide();
    });
    $('#666').click(function(){
       $('#riview').fadeIn();
       $('#qna').hide();
       $('#text').hide();
    });
    $('#777').click(function(){
       $('#riview').hide();
       $('#qna').fadeIn();
       $('#text').hide();
    });
    $('#888').click(function(){
       $('#riview').hide();
       $('#qna').hide();
       $('#text').fadeIn();
    });
   });